
package practica_octavio1.Formulario;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;


public final class Principal extends javax.swing.JFrame {

    
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(this);
        
        SetImageLabel(logoINTRO, "src/practica_octavio1/imagenes/LOGO.png");
        SetImageLabel(EscudoINTRO,"src/practica_octavio1/imagenes/escudo.png" );
    }
    public void SetImageLabel(JLabel labelname, String root){
        ImageIcon image = new ImageIcon (root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelname.getWidth(), labelname.getHeight(), Image.SCALE_DEFAULT));
        labelname.setIcon(icon);
        this.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1INTRO = new javax.swing.JPanel();
        jPanel2INTRO = new javax.swing.JPanel();
        logoINTRO = new javax.swing.JLabel();
        TExtoBienvenidosINTRO = new javax.swing.JLabel();
        BotonEntrarINTRO = new javax.swing.JButton();
        botonRegistrarseINTRO = new javax.swing.JButton();
        EscudoINTRO = new javax.swing.JLabel();
        FondoImagenINTRO = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1INTRO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2INTRO.setBackground(new java.awt.Color(255, 255, 255));

        logoINTRO.setForeground(new java.awt.Color(255, 255, 255));
        logoINTRO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica_octavio1/imagenes/LOGO.png"))); // NOI18N

        TExtoBienvenidosINTRO.setBackground(new java.awt.Color(0, 51, 51));
        TExtoBienvenidosINTRO.setFont(new java.awt.Font("Segoe UI Light", 2, 18)); // NOI18N
        TExtoBienvenidosINTRO.setForeground(new java.awt.Color(0, 0, 0));
        TExtoBienvenidosINTRO.setText("BIENVENIDOS");

        BotonEntrarINTRO.setBackground(new java.awt.Color(58, 107, 113));
        BotonEntrarINTRO.setForeground(new java.awt.Color(255, 255, 255));
        BotonEntrarINTRO.setText("ENTRAR");
        BotonEntrarINTRO.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonEntrarINTRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEntrarINTROActionPerformed(evt);
            }
        });

        botonRegistrarseINTRO.setBackground(new java.awt.Color(14, 33, 40));
        botonRegistrarseINTRO.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistrarseINTRO.setText("REGISTRARSE");
        botonRegistrarseINTRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarseINTROActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2INTROLayout = new javax.swing.GroupLayout(jPanel2INTRO);
        jPanel2INTRO.setLayout(jPanel2INTROLayout);
        jPanel2INTROLayout.setHorizontalGroup(
            jPanel2INTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2INTROLayout.createSequentialGroup()
                .addComponent(logoINTRO, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133)
                .addComponent(TExtoBienvenidosINTRO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(BotonEntrarINTRO, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonRegistrarseINTRO, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel2INTROLayout.setVerticalGroup(
            jPanel2INTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2INTROLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2INTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2INTROLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(TExtoBienvenidosINTRO))
                    .addGroup(jPanel2INTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonRegistrarseINTRO, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BotonEntrarINTRO, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2INTROLayout.createSequentialGroup()
                .addComponent(logoINTRO, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1INTRO.add(jPanel2INTRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 80));

        EscudoINTRO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica_octavio1/imagenes/escudo.png"))); // NOI18N
        EscudoINTRO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1INTRO.add(EscudoINTRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 350, 350));

        FondoImagenINTRO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica_octavio1/imagenes/Fondillo.jpg"))); // NOI18N
        jPanel1INTRO.add(FondoImagenINTRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 810));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1INTRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1INTRO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarseINTROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarseINTROActionPerformed
        Registro registroframe = new Registro();

        registroframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonRegistrarseINTROActionPerformed

    private void BotonEntrarINTROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEntrarINTROActionPerformed
        Entrar entrarframe = new Entrar ();
        
        entrarframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonEntrarINTROActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEntrarINTRO;
    private javax.swing.JLabel EscudoINTRO;
    private javax.swing.JLabel FondoImagenINTRO;
    private javax.swing.JLabel TExtoBienvenidosINTRO;
    private javax.swing.JButton botonRegistrarseINTRO;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1INTRO;
    private javax.swing.JPanel jPanel2INTRO;
    private javax.swing.JLabel logoINTRO;
    // End of variables declaration//GEN-END:variables
}
